FROM golang:1.12-stretch as avro-builder

ENV GOBIN=/go/bin

RUN go get -d github.com/actgardner/gogen-avro/gogen-avro && \
    go install github.com/actgardner/gogen-avro/gogen-avro

FROM golang:1.12-stretch

COPY --from=avro-builder go/bin/gogen-avro /usr/local/bin/gogen-avro

CMD exit 1