FROM golang:1.14-stretch as mockery-builder

RUN go get gopkg.in/yaml.v3 && \
    go get -u -v github.com/vektra/mockery/.../

FROM golang:1.14-stretch

COPY --from=mockery-builder go/bin/mockery /usr/local/bin/mockery

CMD exit 1