FROM golang:1.13-stretch as mockery-builder

RUN go get gopkg.in/yaml.v2 && \
    go get -u -v github.com/vektra/mockery/.../

FROM golang:1.13-stretch

ENV GOFLAGS=-mod=vendor

COPY --from=mockery-builder go/bin/mockery /usr/local/bin/mockery

CMD exit 1