FROM debian:stretch as protoc

ARG DIR=/var/build

RUN apt-get update -y

# source:
# https://github.com/protocolbuffers/protobuf/tree/master/src
RUN apt-get install -y autoconf automake libtool curl make g++ unzip git

RUN git clone -b v3.10.1 https://github.com/protocolbuffers/protobuf.git $DIR

WORKDIR $DIR

RUN git submodule update --init --recursive
RUN ./autogen.sh

RUN ./configure CXXFLAGS="$(pkg-config --cflags protobuf)"
RUN make
RUN make check
RUN make install

FROM golang:1.13-stretch

COPY --from=protoc /usr/local/include/google /usr/local/include/google
COPY --from=protoc /usr/local/bin/protoc /usr/local/bin/protoc
COPY --from=protoc /usr/local/lib/pkgconfig /usr/local/lib/pkgconfig
COPY --from=protoc /usr/local/lib/libprotobuf.so.21 /usr/local/lib/
COPY --from=protoc /usr/local/lib/libprotoc.so.21 /usr/local/lib/

# source:
# https://github.com/gogo/protobuf#more-speed-and-more-generated-code
ARG PROJECT=github.com/gogo/protobuf

# refresh shared library cache.
RUN ldconfig && \
    git clone -b v1.3.1 https://${PROJECT} ${GOPATH}/src/${PROJECT} && \
    (cd ${GOPATH}/src/${PROJECT}; make install)

CMD exit 1