FROM debian:stretch as protoc

ARG DIR=/var/build

RUN apt-get update -y

# source:
# https://github.com/protocolbuffers/protobuf/tree/master/src
RUN apt-get install -y autoconf automake libtool curl make g++ unzip git

RUN git clone https://github.com/protocolbuffers/protobuf.git $DIR

WORKDIR $DIR

RUN git submodule update --init --recursive
RUN ./autogen.sh

RUN ./configure
RUN make
RUN make check
RUN make install

FROM golang:1.12-stretch

COPY --from=protoc /usr/local/include/google /usr/local/include/google
COPY --from=protoc /usr/local/bin/protoc /usr/local/bin/protoc
COPY --from=protoc /usr/local/lib/libproto* /usr/local/lib/
COPY --from=protoc /usr/local/lib/pkgconfig /usr/local/lib/pkgconfig

RUN ldconfig # refresh shared library cache.

# source:
# https://github.com/gogo/protobuf#more-speed-and-more-generated-code
ENV PROJECT=github.com/gogo/protobuf
RUN git clone -b v1.2.1 https://${PROJECT} ${GOPATH}/src/${PROJECT}
RUN cd ${GOPATH}/src/${PROJECT} && make install

CMD exit 1