FROm debian:stretch as kafka-builder

RUN apt-get update -y
RUN apt-get install -y git make g++ zlib1g-dev libssl-dev libsasl2-dev libzstd-dev

WORKDIR /librdkafka

RUN git clone -b master https://github.com/edenhill/librdkafka .

RUN ./configure
RUN make
RUN make install

FROM golang:1.12-stretch as linter-builder

RUN GO111MODULE=on \
    go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.17.0

FROM golang:1.12-stretch

COPY --from=linter-builder go/bin/golangci-lint /usr/local/bin/golangci-lint

COPY --from=kafka-builder /usr/local/include/librdkafka /usr/local/include/librdkafka
COPY --from=kafka-builder /usr/local/lib/librdkafka*.* /usr/local/lib/
COPY --from=kafka-builder /usr/local/lib/pkgconfig /usr/local/lib/pkgconfig

CMD exit 1