FROM golang:1.16-stretch as avro-builder

ARG GOBIN=/go/bin

RUN apt-get update -y && \
    go get github.com/actgardner/gogen-avro/v7/cmd/...

FROM golang:1.16-stretch

COPY --from=avro-builder go/bin/gogen-avro /usr/local/bin/gogen-avro

CMD exit 1