FROm debian:stretch as kafka-builder

RUN apt-get update -y
RUN apt-get install -y git make g++ zlib1g-dev libssl-dev libsasl2-dev libzstd-dev

WORKDIR /librdkafka

RUN git clone -b v1.5.2 https://github.com/edenhill/librdkafka .

RUN ./configure
RUN make
RUN make install

FROM golang:1.15-buster as linter-builder

RUN GOPATH=$(mktemp -d) cd $(mktemp -d); \
    go mod init tempmod; \
    go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0

FROM golang:1.15-buster

COPY --from=linter-builder go/bin/golangci-lint /usr/local/bin/golangci-lint

COPY --from=kafka-builder /usr/local/include/librdkafka /usr/local/include/librdkafka
COPY --from=kafka-builder /usr/local/lib/librdkafka*.* /usr/local/lib/
COPY --from=kafka-builder /usr/local/lib/pkgconfig /usr/local/lib/pkgconfig

CMD exit 1