FROM golang:1.16-stretch as easyjson-builder

ARG GOBIN=/go/bin

RUN apt-get update -y
RUN go get -u github.com/mailru/easyjson/...

FROM golang:1.16-stretch

COPY --from=easyjson-builder go/bin/easyjson /usr/local/bin/easyjson

CMD exit 1